name: Ubuntu
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 6 * * *'
    - cron: '0 12 * * *'
    - cron: '0 18 * * *'
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: arltest
      uses: f1ashine/arltest@master
    
    - name: make files
      run: |
          mkdir output
          git add output/
          git add output/test.txt

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
