name: Ubuntu
on:
  push:
    branches:
      - master
  workflow_run:
   workflows: ["arltest"]
   branches: [master]
   types: 
      - completed
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: arltest
      uses: h0ppays/arltest@master
