name: Ubuntu
on:
  push:
    branches:
      - master
#   schedule:
#     - cron: '0 0 * * *'
#     - cron: '0 6 * * *'
#     - cron: '0 12 * * *'
#     - cron: '0 18 * * *'
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: arltest
      uses: actions/checkout@master
    
    - name: operations
      run: |
          git clone https://github.com/brendan-rius/c-jwt-cracker.git
          cd c-jwt-cracker &&  make
          touch test.txt
          ./jwtcrack eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJvY0VfVDRnal9JWUszeEdRdjZqcXJjZ1hlcmRBIiwiaWF0IjoxNjMwMzE3OTk5LCJleHAiOjE2MzAzMjUxOTl9.wivWGxvBppGX5sfm5BWN2Y-kfDqpIhj_gar57hLu_JnxRE3yqKMTwBH1jb0MU65NQeTJAsplETIonkoRLkMcYA > test.txt
      shell: bash
    
    - name: create changes
      run: |
          git add res.txt

    - name: Commit results to Github
      run: |
          git config --local user.email "xxx@xxx.io"
          git config --global user.name "xxx"
          git commit -m "Scan-Actions report" -a --allow-empty

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
