name: Ubuntu
on:
  workflow_run:
   branches: [main]
   types: 
      - completed
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Debug Session
      uses: h0ppays/arltest@master
